# TODO: update docker version
version: '2.17'

volumes:
  pg_storage:


services:
  pg_cluster_repmgr:
    container_name: pg_cluster_repmgr
    build:
      context: ../../images/pg-repmgr
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - persist-net
    volumes:
      - pg_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
        ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  persist-net:
    external: false
    driver: bridge
