# TODO: update docker version
version: '2.17'
services:

  pg_master:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    networks:
      - persist-net
    ports:
      - "5432:5432"
    volumes:
      #  Base directoryx
      - ./pgbase_dir:/var/lib/postgresql/data

      #  Config
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf

      #  SQL
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./sql/roles.sql:/docker-entrypoint-initdb.d/roles.sql

      # Test data 
      - test_data:/docker-entrypoint-initdb.d/

volumes:
  test_data:
    external:
      name: raw_data_test_data

networks:
  persist-net:
    external: false
    driver: bridge
